import { db, isDatabaseAvailable } from "./db";
import { faqs } from "@shared/schema";

const faqSeedData = [
  {
    service: "accommodation",
    questionPt: "Onde ficam localizados os apartamentos?",
    questionEn: "Where are the apartments located?",
    answerPt: "Os nossos 3 apartamentos ficam no centro da cidade da Horta, na Ilha do Faial, com fácil acesso a restaurantes, marina e principais atrações turísticas.",
    answerEn: "Our 3 apartments are located in the center of Horta city, on Faial Island, with easy access to restaurants, marina and main tourist attractions.",
    keywords: "onde,localização,apartamento,horta,centro,faial",
  },
  {
    service: "accommodation",
    questionPt: "Quantas pessoas os apartamentos acomodam?",
    questionEn: "How many people do the apartments accommodate?",
    answerPt: "Os apartamentos podem acomodar entre 2 a 6 pessoas, dependendo da unidade. Contacte-nos para saber a disponibilidade de cada apartamento.",
    answerEn: "The apartments can accommodate between 2 to 6 people, depending on the unit. Contact us to check availability for each apartment.",
    keywords: "pessoas,capacidade,quartos,acomodar,hóspedes,apartamento",
  },
  {
    service: "accommodation",
    questionPt: "Os apartamentos estão totalmente equipados?",
    questionEn: "Are the apartments fully equipped?",
    answerPt: "Sim! Os apartamentos têm cozinha totalmente equipada com fogão, forno, frigorífico e utensílios. Incluem também Wi-Fi, TV, ar condicionado e roupa de cama.",
    answerEn: "Yes! The apartments have a fully equipped kitchen with stove, oven, refrigerator and utensils. They also include Wi-Fi, TV, air conditioning and bed linen.",
    keywords: "cozinha,equipada,fogão,frigorífico,wifi,tv,ar condicionado",
  },
  {
    service: "accommodation",
    questionPt: "Qual é o horário de check-in e check-out?",
    questionEn: "What are the check-in and check-out times?",
    answerPt: "O check-in é a partir das 15h e o check-out até às 11h. Horários flexíveis podem ser combinados conforme disponibilidade.",
    answerEn: "Check-in is from 3pm and check-out by 11am. Flexible times can be arranged subject to availability.",
    keywords: "check-in,check-out,horário,entrada,saída,hora",
  },
  {
    service: "accommodation",
    questionPt: "Há estacionamento disponível?",
    questionEn: "Is parking available?",
    answerPt: "Sim, há estacionamento gratuito disponível perto dos apartamentos. Podemos fornecer indicações específicas na altura da reserva.",
    answerEn: "Yes, free parking is available near the apartments. We can provide specific directions at the time of booking.",
    keywords: "estacionamento,parque,carro,gratuito,parking",
  },
  {
    service: "accommodation",
    questionPt: "Qual é a estadia mínima nos apartamentos?",
    questionEn: "What is the minimum stay in the apartments?",
    answerPt: "A estadia mínima é geralmente de 2 noites, mas pode variar conforme a época do ano. Contacte-nos para mais informações.",
    answerEn: "The minimum stay is generally 2 nights, but may vary depending on the season. Contact us for more information.",
    keywords: "mínimo,noites,estadia,duração,reserva",
  },
  {
    service: "accommodation",
    questionPt: "Aceitam animais de estimação?",
    questionEn: "Do you accept pets?",
    answerPt: "Alguns apartamentos aceitam animais de estimação mediante consulta prévia. Contacte-nos para verificar disponibilidade e condições.",
    answerEn: "Some apartments accept pets upon prior consultation. Contact us to check availability and conditions.",
    keywords: "animais,estimação,pets,cão,gato,permitido",
  },
  {
    service: "accommodation",
    questionPt: "Os apartamentos têm vista para o mar?",
    questionEn: "Do the apartments have sea views?",
    answerPt: "Alguns dos nossos apartamentos oferecem vista para o mar ou para a marina. Informe-nos da sua preferência ao fazer a reserva.",
    answerEn: "Some of our apartments offer sea or marina views. Let us know your preference when making a reservation.",
    keywords: "vista,mar,marina,paisagem,janela,apartamento",
  },
  {
    service: "events",
    questionPt: "Que tipo de eventos organizam?",
    questionEn: "What type of events do you organize?",
    answerPt: "Organizamos festas de aniversário, despedidas de solteiro(a), eventos corporativos, team building, competições, celebrações ao ar livre e muito mais.",
    answerEn: "We organize birthday parties, bachelor/bachelorette parties, corporate events, team building, competitions, outdoor celebrations and much more.",
    keywords: "eventos,festas,aniversário,despedida,corporativo,team building,tipo",
  },
  {
    service: "events",
    questionPt: "Podem organizar eventos para grupos grandes?",
    questionEn: "Can you organize events for large groups?",
    answerPt: "Sim! Temos experiência com grupos de todas as dimensões, desde pequenas festas a grandes eventos corporativos. Contacte-nos para um orçamento personalizado.",
    answerEn: "Yes! We have experience with groups of all sizes, from small parties to large corporate events. Contact us for a personalized quote.",
    keywords: "grupos,grandes,muitas pessoas,dimensões,orçamento,eventos",
  },
  {
    service: "events",
    questionPt: "Alugam tendas para eventos?",
    questionEn: "Do you rent tents for events?",
    answerPt: "Sim! Temos tendas de grandes dimensões disponíveis para aluguer, perfeitas para festas, eventos ao ar livre, casamentos e celebrações.",
    answerEn: "Yes! We have large tents available for rent, perfect for parties, outdoor events, weddings and celebrations.",
    keywords: "tendas,aluguer,evento,festa,outdoor,casamento",
  },
  {
    service: "events",
    questionPt: "Têm insufláveis para festas de aniversário?",
    questionEn: "Do you have inflatables for birthday parties?",
    answerPt: "Sim! Temos insufláveis divertidos para festas de aniversário infantis. Combinamos atividades como Lasertag e Nerfs para uma festa inesquecível.",
    answerEn: "Yes! We have fun inflatables for children's birthday parties. We combine activities like Lasertag and Nerfs for an unforgettable party.",
    keywords: "insufláveis,aniversário,festa,crianças,infantil,brincar",
  },
  {
    service: "events",
    questionPt: "Organizam eventos de teambuilding para empresas?",
    questionEn: "Do you organize teambuilding events for companies?",
    answerPt: "Sim! Especializamo-nos em eventos de teambuilding com atividades como Lasertag, Paintball, jogos de estratégia e desafios de equipa num ambiente natural único.",
    answerEn: "Yes! We specialize in teambuilding events with activities such as Lasertag, Paintball, strategy games and team challenges in a unique natural environment.",
    keywords: "teambuilding,empresa,corporativo,equipa,atividades,jogos",
  },
  {
    service: "events",
    questionPt: "Qual o preço para organizar um evento?",
    questionEn: "What is the price to organize an event?",
    answerPt: "O preço depende do tipo de evento, número de participantes e atividades escolhidas. Contacte-nos para um orçamento personalizado gratuito.",
    answerEn: "The price depends on the type of event, number of participants and activities chosen. Contact us for a free personalized quote.",
    keywords: "preço,custo,orçamento,evento,quanto,valor",
  },
  {
    service: "general",
    questionPt: "Qual é o horário de funcionamento da Azores4Fun?",
    questionEn: "What are Azores4Fun's opening hours?",
    answerPt: "Estamos disponíveis todos os dias: Segunda a Sexta 9h-19h, Sábado 10h-18h, Domingo 10h-14h. Para urgências, contacte-nos por WhatsApp (+351 969 519 950).",
    answerEn: "We are available every day: Monday to Friday 9am-7pm, Saturday 10am-6pm, Sunday 10am-2pm. For emergencies, contact us via WhatsApp (+351 969 519 950).",
    keywords: "horário,funcionamento,aberto,fechado,horas",
  },
  {
    service: "general",
    questionPt: "Como posso contactar a Azores4Fun?",
    questionEn: "How can I contact Azores4Fun?",
    answerPt: "Pode contactar-nos por telefone (+351 934 993 770), WhatsApp (+351 969 519 950) ou email (info@azores4fun.com). Respondemos rapidamente!",
    answerEn: "You can contact us by phone (+351 934 993 770), WhatsApp (+351 969 519 950) or email (info@azores4fun.com). We respond quickly!",
    keywords: "contacto,telefone,whatsapp,email,falar,ligar,número",
  },
  {
    service: "general",
    questionPt: "Onde fica localizada a Azores4Fun?",
    questionEn: "Where is Azores4Fun located?",
    answerPt: "Estamos localizados na Travessa do Poiso Novo nºs 1 e 3, 9900-000 Horta, Ilha do Faial, Açores, Portugal.",
    answerEn: "We are located at Travessa do Poiso Novo nºs 1 e 3, 9900-000 Horta, Faial Island, Azores, Portugal.",
    keywords: "onde,localização,morada,endereço,local,horta,faial",
  },
  {
    service: "general",
    questionPt: "Aceitam cartão de crédito?",
    questionEn: "Do you accept credit cards?",
    answerPt: "Sim! Aceitamos cartões de crédito/débito, MB Way, transferência bancária e dinheiro. Múltiplas formas de pagamento para sua conveniência.",
    answerEn: "Yes! We accept credit/debit cards, MB Way, bank transfer and cash. Multiple payment methods for your convenience.",
    keywords: "pagamento,cartão,crédito,débito,mbway,dinheiro,pagar,transferência",
  },
  {
    service: "general",
    questionPt: "Têm descontos para grupos?",
    questionEn: "Do you have group discounts?",
    answerPt: "Sim! Oferecemos descontos especiais para grupos em todas as nossas atividades e alojamento. Contacte-nos para um orçamento personalizado.",
    answerEn: "Yes! We offer special discounts for groups on all our activities and accommodation. Contact us for a personalized quote.",
    keywords: "desconto,grupo,promoção,oferta,preço especial",
  },
  {
    service: "general",
    questionPt: "Falam inglês?",
    questionEn: "Do you speak English?",
    answerPt: "Sim! A nossa equipa fala português e inglês fluentemente. Estamos preparados para receber turistas internacionais.",
    answerEn: "Yes! Our team speaks fluent Portuguese and English. We are prepared to receive international tourists.",
    keywords: "inglês,português,língua,idioma,falar,comunicar",
  },
  {
    service: "general",
    questionPt: "Como chego à Ilha do Faial?",
    questionEn: "How do I get to Faial Island?",
    answerPt: "Pode chegar ao Faial por avião (voos de Lisboa, Porto e outras ilhas) ou por ferry (ligação regular com Pico e São Jorge). O aeroporto fica a 10 minutos da Horta.",
    answerEn: "You can reach Faial by plane (flights from Lisbon, Porto and other islands) or by ferry (regular connection with Pico and São Jorge). The airport is 10 minutes from Horta.",
    keywords: "chegar,faial,avião,ferry,barco,voo,transporte",
  },
  {
    service: "general",
    questionPt: "Qual a melhor época para visitar os Açores?",
    questionEn: "What is the best time to visit the Azores?",
    answerPt: "Os Açores podem ser visitados durante todo o ano! O verão (junho-setembro) tem mais sol, enquanto a primavera e outono oferecem temperaturas amenas e menos turistas.",
    answerEn: "The Azores can be visited year-round! Summer (June-September) has more sun, while spring and autumn offer mild temperatures and fewer tourists.",
    keywords: "época,visitar,melhor,tempo,clima,açores,quando",
  },
  {
    service: "general",
    questionPt: "É seguro praticar atividades ao ar livre nos Açores?",
    questionEn: "Is it safe to do outdoor activities in the Azores?",
    answerPt: "Sim! Os Açores são muito seguros. Todas as nossas atividades incluem equipamento de segurança e briefing. Em caso de condições meteorológicas adversas, reagendamos sem custos.",
    answerEn: "Yes! The Azores are very safe. All our activities include safety equipment and briefing. In case of adverse weather conditions, we reschedule at no cost.",
    keywords: "seguro,segurança,atividades,outdoor,clima,açores",
  },
  {
    service: "general",
    questionPt: "As atividades funcionam com chuva?",
    questionEn: "Do activities run in the rain?",
    answerPt: "Depende da atividade e intensidade da chuva. Atividades como Lasertag podem decorrer com chuva ligeira. Em caso de mau tempo severo, reagendamos sem custos adicionais.",
    answerEn: "It depends on the activity and rain intensity. Activities like Lasertag can run in light rain. In case of severe bad weather, we reschedule at no additional cost.",
    keywords: "chuva,tempo,meteorologia,cancelar,reagendar,atividade",
  },
  {
    service: "general",
    questionPt: "Posso combinar várias atividades num pacote?",
    questionEn: "Can I combine multiple activities in a package?",
    answerPt: "Sim! Oferecemos pacotes combinados com desconto. Por exemplo, tour + atividade, alojamento + tour, ou eventos com múltiplas atividades. Contacte-nos para personalizar.",
    answerEn: "Yes! We offer combined packages with discounts. For example, tour + activity, accommodation + tour, or events with multiple activities. Contact us to customize.",
    keywords: "pacote,combinar,atividades,desconto,personalizado",
  },
  {
    service: "general",
    questionPt: "Têm seguro para as atividades?",
    questionEn: "Do you have insurance for activities?",
    answerPt: "Sim! Todas as nossas atividades de animação turística têm seguro de responsabilidade civil. A sua segurança é a nossa prioridade.",
    answerEn: "Yes! All our tourist entertainment activities have civil liability insurance. Your safety is our priority.",
    keywords: "seguro,responsabilidade,segurança,atividades,cobertura",
  },
  {
    service: "general",
    questionPt: "Qual é o número de WhatsApp?",
    questionEn: "What is the WhatsApp number?",
    answerPt: "O nosso WhatsApp é +351 969 519 950. É a forma mais rápida de nos contactar para reservas e informações.",
    answerEn: "Our WhatsApp is +351 969 519 950. It's the fastest way to contact us for bookings and information.",
    keywords: "whatsapp,número,contacto,mensagem,chat",
  },
  {
    service: "general",
    questionPt: "Como faço uma reserva?",
    questionEn: "How do I make a booking?",
    answerPt: "Pode reservar através do nosso site, WhatsApp (+351 969 519 950), telefone (+351 934 993 770), email ou presencialmente na nossa loja na Horta.",
    answerEn: "You can book through our website, WhatsApp (+351 969 519 950), phone (+351 934 993 770), email or in person at our shop in Horta.",
    keywords: "reservar,reserva,booking,marcar,agendar,como",
  },
  {
    service: "general",
    questionPt: "Qual a política de cancelamento?",
    questionEn: "What is the cancellation policy?",
    answerPt: "Cancelamentos até 48h antes têm reembolso total. Cancelamentos com menos de 48h podem ter condições específicas. Contacte-nos para mais detalhes.",
    answerEn: "Cancellations up to 48h before have full refund. Cancellations with less than 48h may have specific conditions. Contact us for more details.",
    keywords: "cancelamento,reembolso,política,anular,cancelar",
  },
  {
    service: "kayak",
    questionPt: "Preciso de experiência prévia para alugar kayak ou SUP?",
    questionEn: "Do I need prior experience to rent kayak or SUP?",
    answerPt: "Não é necessário. Damos um briefing de segurança e instruções básicas antes de cada aluguer. É perfeito para todos os níveis de experiência.",
    answerEn: "No experience needed. We provide a safety briefing and basic instructions before each rental. It's perfect for all experience levels.",
    keywords: "experiência,iniciante,principiante,kayak,sup,alugar,aluguer",
  },
  {
    service: "kayak",
    questionPt: "Onde posso usar o kayak ou SUP?",
    questionEn: "Where can I use the kayak or SUP?",
    answerPt: "Disponível na Marina da Horta e Porto Pim, duas das zonas mais bonitas e seguras da ilha, com águas cristalinas ideais para desportos aquáticos.",
    answerEn: "Available at Marina da Horta and Porto Pim, two of the most beautiful and safe areas of the island, with crystal clear waters ideal for water sports.",
    keywords: "onde,local,marina,horta,porto pim,kayak,sup,baía",
  },
  {
    service: "kayak",
    questionPt: "O equipamento de segurança está incluído no aluguer?",
    questionEn: "Is safety equipment included in the rental?",
    answerPt: "Sim, fornecemos colete salva-vidas e todo o equipamento necessário para uma experiência segura nas águas do Faial.",
    answerEn: "Yes, we provide life jacket and all necessary equipment for a safe experience in the waters of Faial.",
    keywords: "segurança,colete,salva-vidas,equipamento,incluído,kayak,sup",
  },
  {
    service: "kayak",
    questionPt: "Quanto custa alugar kayak ou SUP?",
    questionEn: "How much does it cost to rent kayak or SUP?",
    answerPt: "Os preços variam conforme a duração do aluguer. Contacte-nos para obter os preços atualizados e pacotes especiais para grupos.",
    answerEn: "Prices vary according to rental duration. Contact us for updated prices and special group packages.",
    keywords: "preço,custo,quanto,kayak,sup,aluguer,valor",
  },
  {
    service: "kayak",
    questionPt: "Posso alugar equipamento de snorkeling?",
    questionEn: "Can I rent snorkeling equipment?",
    answerPt: "Sim! Oferecemos material de snorkeling para explorar a vida marinha vibrante das águas cristalinas dos Açores.",
    answerEn: "Yes! We offer snorkeling equipment to explore the vibrant marine life in the crystal clear waters of the Azores.",
    keywords: "snorkeling,mergulho,máscara,barbatanas,aluguer,equipamento",
  },
  {
    service: "kayak",
    questionPt: "O SUP é difícil de aprender?",
    questionEn: "Is SUP difficult to learn?",
    answerPt: "Não! O Stand Up Paddle é fácil de aprender. A maioria das pessoas consegue manter o equilíbrio e remar confortavelmente em poucos minutos.",
    answerEn: "No! Stand Up Paddle is easy to learn. Most people can balance and paddle comfortably within minutes.",
    keywords: "sup,paddle,difícil,aprender,fácil,equilíbrio",
  },
  {
    service: "lasertag",
    questionPt: "O LaserTag dói como o paintball?",
    questionEn: "Does LaserTag hurt like paintball?",
    answerPt: "Não! O LaserTag usa sensores infravermelhos, sem qualquer impacto físico. É perfeito para todas as idades, incluindo crianças.",
    answerEn: "No! LaserTag uses infrared sensors, with no physical impact. It's perfect for all ages, including children.",
    keywords: "dói,dor,impacto,seguro,lasertag,laser,crianças",
  },
  {
    service: "lasertag",
    questionPt: "Qual a idade mínima para LaserTag?",
    questionEn: "What is the minimum age for LaserTag?",
    answerPt: "Não há idade mínima rígida. É adequado para crianças a partir dos 6 anos, tornando-o ideal para festas de aniversário infantis.",
    answerEn: "There is no strict minimum age. It is suitable for children from 6 years old, making it ideal for children's birthday parties.",
    keywords: "idade,mínima,criança,lasertag,anos,aniversário,festa",
  },
  {
    service: "lasertag",
    questionPt: "O LaserTag pode ser jogado em qualquer lugar?",
    questionEn: "Can LaserTag be played anywhere?",
    answerPt: "Sim! O LaserTag pode ser jogado indoor ou outdoor. Podemos organizar jogos no nosso campo ou levar o equipamento ao seu evento, festa ou local preferido.",
    answerEn: "Yes! LaserTag can be played indoor or outdoor. We can organize games at our field or bring the equipment to your event, party or preferred location.",
    keywords: "onde,local,indoor,outdoor,lasertag,evento,festa",
  },
  {
    service: "lasertag",
    questionPt: "Quanto dura uma sessão de LaserTag?",
    questionEn: "How long does a LaserTag session last?",
    answerPt: "Uma sessão típica dura cerca de 1-2 horas, incluindo briefing de segurança e múltiplas partidas. Podemos adaptar a duração conforme o seu evento.",
    answerEn: "A typical session lasts about 1-2 hours, including safety briefing and multiple games. We can adapt the duration according to your event.",
    keywords: "duração,tempo,horas,sessão,lasertag,quanto",
  },
  {
    service: "paintball",
    questionPt: "Qual é a idade mínima para jogar paintball?",
    questionEn: "What is the minimum age to play paintball?",
    answerPt: "A idade mínima é 10 anos. Menores devem estar acompanhados por um adulto responsável.",
    answerEn: "The minimum age is 10 years old. Minors must be accompanied by a responsible adult.",
    keywords: "idade,mínima,anos,criança,menor,paintball,jogar",
  },
  {
    service: "paintball",
    questionPt: "O equipamento de paintball está incluído no preço?",
    questionEn: "Is paintball equipment included in the price?",
    answerPt: "Sim! O preço inclui máscara de proteção, marcador (arma), colete e bolas de tinta. Todo o equipamento necessário está incluído.",
    answerEn: "Yes! The price includes protective mask, marker (gun), vest and paintballs. All necessary equipment is included.",
    keywords: "equipamento,incluído,preço,máscara,marcador,colete,bolas,material",
  },
  {
    service: "paintball",
    questionPt: "Preciso de reservar paintball com antecedência?",
    questionEn: "Do I need to book paintball in advance?",
    answerPt: "Sim, recomendamos reservar pelo menos 24 horas antes para garantir disponibilidade. Pode reservar online, por telefone (+351 934 993 770) ou WhatsApp (+351 969 519 950).",
    answerEn: "Yes, we recommend booking at least 24 hours in advance to ensure availability. You can book online, by phone (+351 934 993 770) or WhatsApp (+351 969 519 950).",
    keywords: "reservar,antecedência,marcação,agendar,disponibilidade,paintball",
  },
  {
    service: "paintball",
    questionPt: "Onde fica o campo de paintball?",
    questionEn: "Where is the paintball field located?",
    answerPt: "Temos um campo exclusivo preparado na Ilha do Faial, Açores. O local exato é comunicado após a reserva para garantir a sua privacidade.",
    answerEn: "We have an exclusive prepared field on Faial Island, Azores. The exact location is communicated after booking to ensure privacy.",
    keywords: "onde,localização,campo,faial,açores,local,paintball",
  },
  {
    service: "paintball",
    questionPt: "As bolas de paintball são biodegradáveis?",
    questionEn: "Are paintball balls biodegradable?",
    answerPt: "Sim! As nossas bolas de Paintball e Gelblaster são biodegradáveis. Depois de uma normal chuvinha, a tinta desaparece completamente, não deixando vestígios na paisagem.",
    answerEn: "Yes! Our Paintball and Gelblaster balls are biodegradable. After a normal rain, the paint disappears completely, leaving no traces in the landscape.",
    keywords: "biodegradável,ecológico,tinta,ambiente,sustentável,paintball",
  },
  {
    service: "paintball",
    questionPt: "O paintball dói muito?",
    questionEn: "Does paintball hurt a lot?",
    answerPt: "As bolas de paintball podem causar um ligeiro impacto, mas com o equipamento de proteção fornecido, é seguro e confortável. Se preferir algo sem impacto, experimente o Lasertag!",
    answerEn: "Paintball balls can cause a slight impact, but with the protective equipment provided, it's safe and comfortable. If you prefer no impact, try Lasertag!",
    keywords: "dói,dor,impacto,seguro,proteção,paintball",
  },
  {
    service: "paintball",
    questionPt: "Qual a diferença entre Paintball, Gelblaster, Lasertag e Nerfs?",
    questionEn: "What is the difference between Paintball, Gelblaster, Lasertag and Nerfs?",
    answerPt: "Paintball usa bolas de tinta com impacto médio. Gelblaster usa gel biodegradável com impacto leve. Lasertag usa sensores infravermelhos sem impacto. Nerfs usam dardos de espuma suaves. Todos são seguros e divertidos!",
    answerEn: "Paintball uses paint balls with medium impact. Gelblaster uses biodegradable gel with light impact. Lasertag uses infrared sensors with no impact. Nerfs use soft foam darts. All are safe and fun!",
    keywords: "diferença,paintball,gelblaster,lasertag,nerfs,comparar,tipo",
  },
  {
    service: "paintball",
    questionPt: "Quantas pessoas podem jogar paintball?",
    questionEn: "How many people can play paintball?",
    answerPt: "Podemos organizar jogos para grupos de 6 a 40+ pessoas. Para grupos maiores, contacte-nos para um orçamento personalizado para eventos ou teambuilding.",
    answerEn: "We can organize games for groups of 6 to 40+ people. For larger groups, contact us for a personalized quote for events or teambuilding.",
    keywords: "pessoas,grupo,quantos,capacidade,paintball,teambuilding",
  },
  {
    service: "realestate",
    questionPt: "Que serviços de gestão imobiliária oferecem?",
    questionEn: "What property management services do you offer?",
    answerPt: "Oferecemos gestão completa de propriedades: arrendamento de longa duração, manutenção, limpeza, check-in/check-out de hóspedes, marketing e construção.",
    answerEn: "We offer complete property management: long-term rental, maintenance, cleaning, guest check-in/check-out, marketing and construction.",
    keywords: "gestão,imobiliária,propriedade,manutenção,aluguer,arrendamento,serviços",
  },
  {
    service: "realestate",
    questionPt: "Gerem propriedades para aluguer de férias?",
    questionEn: "Do you manage vacation rental properties?",
    answerPt: "Sim! Especializamo-nos em gestão de propriedades para aluguer de curta duração, alojamento local, Airbnb e Booking.",
    answerEn: "Yes! We specialize in managing properties for short-term rental, local accommodation, Airbnb and Booking.",
    keywords: "férias,aluguer,curta duração,airbnb,alojamento local,booking",
  },
  {
    service: "realestate",
    questionPt: "Fazem manutenção de propriedades?",
    questionEn: "Do you do property maintenance?",
    answerPt: "Sim! Oferecemos serviços de manutenção preventiva e corretiva, incluindo reparações, pintura, jardinagem e limpezas regulares.",
    answerEn: "Yes! We offer preventive and corrective maintenance services, including repairs, painting, gardening and regular cleaning.",
    keywords: "manutenção,reparação,limpeza,conservação,propriedade",
  },
  {
    service: "realestate",
    questionPt: "Oferecem serviços de construção?",
    questionEn: "Do you offer construction services?",
    answerPt: "Sim! Temos serviços de construção e renovação para empreendimentos turísticos e particulares nos Açores.",
    answerEn: "Yes! We have construction and renovation services for tourist developments and private properties in the Azores.",
    keywords: "construção,renovação,obras,empreitada,imobiliária",
  },
  {
    service: "realestate",
    questionPt: "Como funciona a gestão de alojamento local?",
    questionEn: "How does local accommodation management work?",
    answerPt: "Tratamos de tudo: marketing e anúncios, gestão de reservas, comunicação com hóspedes, check-in/check-out, limpezas e manutenção. Maximize o rendimento da sua propriedade.",
    answerEn: "We handle everything: marketing and listings, booking management, guest communication, check-in/check-out, cleaning and maintenance. Maximize your property income.",
    keywords: "gestão,alojamento local,reservas,hóspedes,rendimento",
  },
  {
    service: "shop",
    questionPt: "Que produtos vendem na loja?",
    questionEn: "What products do you sell in the shop?",
    answerPt: "Vendemos merchandising Azores4Fun (t-shirts, bonés, etc.), produtos locais dos Açores, artesanato regional e souvenirs únicos.",
    answerEn: "We sell Azores4Fun merchandise (t-shirts, caps, etc.), local Azorean products, regional crafts and unique souvenirs.",
    keywords: "loja,produtos,merchandising,t-shirts,bonés,açores,local,souvenirs",
  },
  {
    service: "shop",
    questionPt: "Fazem envios para fora da ilha?",
    questionEn: "Do you ship outside the island?",
    answerPt: "Sim, fazemos envios para Portugal continental e outros destinos. Contacte-nos para mais informações sobre portes e prazos.",
    answerEn: "Yes, we ship to mainland Portugal and other destinations. Contact us for more information about shipping costs and times.",
    keywords: "envio,entrega,enviar,correio,porte,expedição,fora",
  },
  {
    service: "shop",
    questionPt: "Onde fica a loja Azores4Fun?",
    questionEn: "Where is the Azores4Fun shop located?",
    answerPt: "A nossa loja fica no centro da Horta, na Travessa do Poiso Novo. É também o ponto de receção para reservas de atividades e tours.",
    answerEn: "Our shop is located in the center of Horta, at Travessa do Poiso Novo. It is also the reception point for activity and tour bookings.",
    keywords: "loja,onde,localização,horta,morada,endereço",
  },
  {
    service: "shop",
    questionPt: "Qual o horário de funcionamento da loja?",
    questionEn: "What are the shop opening hours?",
    answerPt: "Segunda a Sexta: 9h-19h. Sábado: 10h-18h. Domingo: 10h-14h. Horários podem variar em época alta.",
    answerEn: "Monday to Friday: 9am-7pm. Saturday: 10am-6pm. Sunday: 10am-2pm. Hours may vary during high season.",
    keywords: "horário,funcionamento,aberto,fechado,horas,loja",
  },
  {
    service: "shop",
    questionPt: "Posso fazer reservas de atividades na loja?",
    questionEn: "Can I book activities at the shop?",
    answerPt: "Sim! A loja é o nosso ponto de receção principal. Pode fazer reservas presenciais para todas as nossas atividades, tours e alojamento.",
    answerEn: "Yes! The shop is our main reception point. You can make in-person bookings for all our activities, tours and accommodation.",
    keywords: "reserva,atividades,loja,presencial,marcação",
  },
  {
    service: "tattoo",
    questionPt: "Quem é a artista do estúdio de tatuagem?",
    questionEn: "Who is the tattoo studio artist?",
    answerPt: "A nossa artista é a Catarina Gomes, com anos de experiência em diversos estilos. Siga o trabalho dela no Instagram @catarinagomestattoo.",
    answerEn: "Our artist is Catarina Gomes, with years of experience in various styles. Follow her work on Instagram @catarinagomestattoo.",
    keywords: "artista,catarina,gomes,quem,estúdio,instagram,tatuadora",
  },
  {
    service: "tattoo",
    questionPt: "Preciso de marcar consulta prévia para tatuagem?",
    questionEn: "Do I need to book a prior consultation for a tattoo?",
    answerPt: "Sim, recomendamos uma consulta prévia gratuita para discutir o design, tamanho, localização e orçamento da tatuagem. Assim garantimos que o resultado será exatamente o que pretende.",
    answerEn: "Yes, we recommend a free prior consultation to discuss the design, size, placement and budget of the tattoo. This ensures the result will be exactly what you want.",
    keywords: "consulta,marcação,agendar,prévia,reservar,tatuagem",
  },
  {
    service: "tattoo",
    questionPt: "Que estilo de tatuagem fazem?",
    questionEn: "What tattoo style do you do?",
    answerPt: "Fazemos Fineline.",
    answerEn: "We do Fineline.",
    keywords: "estilos,fineline,minimalista,watercolor,realismo,geométrico,tradicional",
  },
  {
    service: "tattoo",
    questionPt: "Fazem piercings também?",
    questionEn: "Do you also do piercings?",
    answerPt: "Sim! Oferecemos vários tipos de piercings: lóbulo, hélix, tragus, nostril, septo, sobrancelha, língua, umbigo e microdermal.",
    answerEn: "Yes! We offer various types of piercings: lobe, helix, tragus, nostril, septum, eyebrow, tongue, navel and microdermal.",
    keywords: "piercing,piercings,lóbulo,hélix,tragus,nostril,septo,umbigo",
  },
  {
    service: "tattoo",
    questionPt: "O estúdio de tatuagem é higiénico e seguro?",
    questionEn: "Is the tattoo studio hygienic and safe?",
    answerPt: "Absolutamente! Seguimos todos os protocolos de higiene e usamos materiais esterilizados e descartáveis. A segurança e saúde dos clientes é a nossa prioridade.",
    answerEn: "Absolutely! We follow all hygiene protocols and use sterilized and disposable materials. Customer safety and health is our priority.",
    keywords: "higiene,segurança,esterilizado,descartável,limpo,protocolos,saúde",
  },
  {
    service: "tattoo",
    questionPt: "Qual é o tempo de cicatrização de uma tatuagem?",
    questionEn: "What is the healing time for a tattoo?",
    answerPt: "O tempo de cicatrização varia de 2 a 4 semanas para a camada superficial. Fornecemos instruções detalhadas de cuidados pós-tatuagem para garantir uma cicatrização perfeita.",
    answerEn: "Healing time varies from 2 to 4 weeks for the surface layer. We provide detailed aftercare instructions to ensure perfect healing.",
    keywords: "cicatrização,tempo,cuidados,recuperação,healing,tatuagem",
  },
  {
    service: "tattoo",
    questionPt: "Quanto custa uma tatuagem?",
    questionEn: "How much does a tattoo cost?",
    answerPt: "O preço depende do tamanho, complexidade e tempo necessário. Agende uma consulta gratuita para obter um orçamento personalizado para o seu projeto.",
    answerEn: "The price depends on size, complexity and time required. Schedule a free consultation to get a personalized quote for your project.",
    keywords: "preço,custo,quanto,valor,orçamento,tatuagem",
  },
  {
    service: "tattoo",
    questionPt: "Qual a idade mínima para fazer tatuagem?",
    questionEn: "What is the minimum age for a tattoo?",
    answerPt: "A idade mínima legal é 18 anos. Menores de idade não podem fazer tatuagens, mesmo com autorização dos pais.",
    answerEn: "The legal minimum age is 18 years old. Minors cannot get tattoos, even with parental consent.",
    keywords: "idade,mínima,anos,menor,tatuagem,legal",
  },
  {
    service: "tattoo",
    questionPt: "Posso trazer o meu próprio design de tatuagem?",
    questionEn: "Can I bring my own tattoo design?",
    answerPt: "Sim! Pode trazer o seu design ou uma referência. A Catarina trabalha consigo para adaptar e aperfeiçoar o conceito até ficar perfeito.",
    answerEn: "Yes! You can bring your design or a reference. Catarina works with you to adapt and perfect the concept until it's perfect.",
    keywords: "design,próprio,desenho,referência,ideia,tatuagem",
  },
  {
    service: "tattoo",
    questionPt: "Fazem cover-up de tatuagens antigas?",
    questionEn: "Do you do cover-up of old tattoos?",
    answerPt: "Sim, fazemos cover-ups! Agende uma consulta para avaliarmos a tatuagem existente e discutirmos as melhores opções para cobrir ou transformar.",
    answerEn: "Yes, we do cover-ups! Schedule a consultation so we can evaluate the existing tattoo and discuss the best options to cover or transform it.",
    keywords: "cover-up,cobrir,tatuagem antiga,transformar,corrigir",
  },
  {
    service: "tattoo",
    questionPt: "Quanto tempo demora uma sessão de tatuagem?",
    questionEn: "How long does a tattoo session take?",
    answerPt: "O tempo varia conforme o tamanho e a complexidade do design. Tatuagens pequenas podem levar 1-2 horas, enquanto peças maiores podem necessitar de várias sessões de 4-6 horas cada.",
    answerEn: "The time varies depending on the size and complexity of the design. Small tattoos can take 1-2 hours, while larger pieces may require multiple sessions of 4-6 hours each.",
  },
  {
    service: "tattoo",
    questionPt: "Posso pedir um orçamento antes?",
    questionEn: "Can I request a quote beforehand?",
    answerPt: "Sim! Para um orçamento correto preciso sempre de: Referências do estilo/design, tamanho aproximado (em cm) e local do corpo.",
    answerEn: "Yes! For an accurate quote I always need: Style/design references, approximate size (in cm) and body location.",
  },
  {
    service: "tattoo",
    questionPt: "Fazes projetos personalizados?",
    questionEn: "Do you do custom designs?",
    answerPt: "Sim! Adoro criar projetos completamente personalizados. Cada cliente é único e merece uma tatuagem única. Trabalho contigo desde a ideia inicial até ao design final para garantir que o resultado seja exatamente o que querias.",
    answerEn: "Yes! I love creating completely personalized designs. Each client is unique and deserves a unique tattoo. I work with you from the initial idea to the final design to ensure the result is exactly what you wanted.",
  },
  {
    service: "tattoo",
    questionPt: "Fazes tatuagens de cor?",
    questionEn: "Do you do color tattoos?",
    answerPt: "Trabalho exclusivamente com pigmento preto, e eventualmente pequenos detalhes em vermelho. Não trabalho com outros pigmentos coloridos.",
    answerEn: "I work exclusively with black pigment, and occasionally small details in red. I do not work with other colored pigments.",
  },
  {
    service: "tattoo",
    questionPt: "As tatuagens nos dedos/mãos/pés/costelas têm algum risco extra?",
    questionEn: "Do tattoos on fingers/hands/feet/ribs have extra risks?",
    answerPt: "Sim. Algumas zonas têm maior probabilidade de: Desbotar rapidamente, perder claridade, necessitar retoque cedo e ter menor duração.",
    answerEn: "Yes. Some areas are more likely to: Fade quickly, lose clarity, need early touch-ups and have shorter duration.",
  },
  {
    service: "tattoo",
    questionPt: "A tatuagem dói muito?",
    questionEn: "Does getting a tattoo hurt a lot?",
    answerPt: "A dor varia de pessoa para pessoa e depende da localização da tatuagem. Áreas com mais gordura e músculo geralmente doem menos que áreas ósseas. A maioria das pessoas descreve como um desconforto tolerável.",
    answerEn: "Pain varies from person to person and depends on the tattoo location. Areas with more fat and muscle generally hurt less than bony areas. Most people describe it as tolerable discomfort.",
  },
  {
    service: "tattoo",
    questionPt: "Usas pomada anestésica?",
    questionEn: "Do you use numbing cream?",
    answerPt: "Não utilizo pomada anestésica por questões de segurança, eficácia reduzida e possibilidade de reação alérgica.",
    answerEn: "I do not use numbing cream due to safety concerns, reduced effectiveness and possibility of allergic reaction.",
  },
  {
    service: "tattoo",
    questionPt: "Quais são os cuidados após a tatuagem?",
    questionEn: "What is the aftercare for a tattoo?",
    answerPt: "Mantém a área limpa e hidratada. Lave suavemente 2-3 vezes ao dia com sabão neutro, aplique pomada recomendada, evite exposição solar direta, piscinas e praias por 2-3 semanas. Não coce ou arranhe a tatuagem durante a cicatrização.",
    answerEn: "Keep the area clean and moisturized. Wash gently 2-3 times a day with neutral soap, apply recommended ointment, avoid direct sun exposure, pools and beaches for 2-3 weeks. Do not scratch or pick at the tattoo during healing.",
  },
  {
    service: "tattoo",
    questionPt: "Posso fazer uma tatuagem se tiver alergia?",
    questionEn: "Can I get a tattoo if I have allergies?",
    answerPt: "Se tem histórico de alergias a tintas ou metais, informe-me antes da sessão. Podemos fazer um teste de patch com a tinta para garantir que não há reação alérgica.",
    answerEn: "If you have a history of allergies to inks or metals, please inform me before the session. We can do a patch test with the ink to ensure there is no allergic reaction.",
  },
  {
    service: "tattoo",
    questionPt: "As tintas são seguras?",
    questionEn: "Are the inks safe?",
    answerPt: "Uso apenas tintas aprovadas e regulamentadas pela UE.",
    answerEn: "I only use inks approved and regulated by the EU.",
  },
  {
    service: "tattoo",
    questionPt: "Que materiais utilizas nas perfurações?",
    questionEn: "What materials do you use for piercings?",
    answerPt: "Uso exclusivamente titânio de grau implante — hipoalergénico e biocompatível, o material mais seguro para perfurações iniciais.",
    answerEn: "I exclusively use implant-grade titanium — hypoallergenic and biocompatible, the safest material for initial piercings.",
  },
  {
    service: "tattoo",
    questionPt: "Fazes piercings nos mamilos?",
    questionEn: "Do you do nipple piercings?",
    answerPt: "Atualmente não faço piercings nos mamilos ou perfurações íntimas.",
    answerEn: "I currently do not do nipple piercings or intimate piercings.",
  },
  {
    service: "tattoo",
    questionPt: "Usas anestesia para piercings?",
    questionEn: "Do you use anesthesia for piercings?",
    answerPt: "Não. Pomadas anestésicas podem alterar a textura da pele, aumentar sangramento e gerar reações alérgicas. O processo é rápido e seguro sem anestesia.",
    answerEn: "No. Numbing creams can alter skin texture, increase bleeding and cause allergic reactions. The process is quick and safe without anesthesia.",
  },
  {
    service: "tattoo",
    questionPt: "Posso escolher qualquer jóia para o piercing?",
    questionEn: "Can I choose any jewelry for the piercing?",
    answerPt: "Para a perfuração inicial, não. É necessário usar joias específicas, esterilizadas e adequadas ao processo de cicatrização. Depois de cicatrizar, podes usar joias de outros modelos.",
    answerEn: "For the initial piercing, no. You need to use specific, sterilized jewelry suitable for the healing process. After healing, you can use jewelry of other styles.",
  },
  {
    service: "tattoo",
    questionPt: "Quando posso trocar a jóia do piercing?",
    questionEn: "When can I change my piercing jewelry?",
    answerPt: "Depende da perfuração: Lóbulo: 2-3 meses, Nariz: 4-6 meses, Cartilagem: 6-12 meses, Hélice/Tragus/etc: até 1 ano. Trocar cedo demais é a maior causa de complicações.",
    answerEn: "It depends on the piercing: Lobe: 2-3 months, Nose: 4-6 months, Cartilage: 6-12 months, Helix/Tragus/etc: up to 1 year. Changing too early is the biggest cause of complications.",
  },
  {
    service: "tattoo",
    questionPt: "É normal ter um \"caroço\" ou bolinha ao lado do piercing?",
    questionEn: "Is it normal to have a bump next to the piercing?",
    answerPt: "Sim. Isso chama-se granuloma (ou quelóide inflamatório). É comum e geralmente causado por: fricção, dormir em cima, tocar constantemente, jóia inadequada ou infeções leves. Por norma, é tratável.",
    answerEn: "Yes. This is called a granuloma (or inflammatory keloid). It is common and usually caused by: friction, sleeping on it, touching constantly, inadequate jewelry or mild infections. It is usually treatable.",
  },
  {
    service: "tattoo",
    questionPt: "Posso fazer desporto, ginásio ou nadar com piercing novo?",
    questionEn: "Can I exercise, go to the gym or swim with a new piercing?",
    answerPt: "Evita durante as primeiras semanas: piscinas, mar, saunas, desporto de contacto e capacetes/auscultadores sobre a zona.",
    answerEn: "Avoid during the first weeks: pools, sea, saunas, contact sports and helmets/headphones over the area.",
  },
  {
    service: "tattoo",
    questionPt: "Podem reabrir o meu piercing antigo?",
    questionEn: "Can you reopen my old piercing?",
    answerPt: "Sim, se a perfuração estiver saudável, sem nódulos, e ainda existir um canal. Se estiver completamente fechado ou inflamado, é mais seguro refazer do zero.",
    answerEn: "Yes, if the piercing is healthy, without nodules, and a channel still exists. If it is completely closed or inflamed, it is safer to redo from scratch.",
  },
  {
    service: "tattoo",
    questionPt: "O material é esterilizado?",
    questionEn: "Is the material sterilized?",
    answerPt: "Sim. Usamos materiais descartáveis a cada utilização, joias pré-esterilizadas e superfícies recorrentemente desinfetadas com técnicas de antissepsia.",
    answerEn: "Yes. We use disposable materials for each use, pre-sterilized jewelry and surfaces regularly disinfected with antiseptic techniques.",
  },
  {
    service: "tattoo",
    questionPt: "O que devo fazer no dia da tatuagem/piercing?",
    questionEn: "What should I do on the day of my tattoo/piercing?",
    answerPt: "Trazer documento de identificação (obrigatório para menores de 18 com responsável presente), ter a pele limpa, não beber álcool ou tomar calmantes nas 24h anteriores e comer antes da sessão.",
    answerEn: "Bring ID (mandatory for under 18s with a guardian present), have clean skin, do not drink alcohol or take sedatives 24h before and eat before the session.",
  },
  {
    service: "tattoo",
    questionPt: "Posso levar acompanhante?",
    questionEn: "Can I bring someone with me?",
    answerPt: "Sim, é permitido 1 acompanhante, desde que respeite as regras do estúdio e não interfira no processo.",
    answerEn: "Yes, 1 companion is allowed, as long as they respect the studio rules and do not interfere with the process.",
  },
  {
    service: "tattoo",
    questionPt: "Como posso marcar uma sessão?",
    questionEn: "How can I book a session?",
    answerPt: "Podes marcar via Instagram, Facebook ou Email.",
    answerEn: "You can book via Instagram, Facebook or Email.",
  },
  {
    service: "tattoo",
    questionPt: "Posso fazer tatuagem/piercing se estiver grávida ou a amamentar?",
    questionEn: "Can I get a tattoo/piercing if I am pregnant or breastfeeding?",
    answerPt: "Não é recomendado fazer tatuagens ou piercings durante a gravidez ou amamentação devido ao stress que pode causar ao corpo. É melhor esperar até após este período.",
    answerEn: "It is not recommended to get tattoos or piercings during pregnancy or breastfeeding due to the stress it can cause to the body. It is better to wait until after this period.",
  },
  {
    service: "tours",
    questionPt: "Quanto tempo dura o tour da ilha?",
    questionEn: "How long does the island tour take?",
    answerPt: "Os tours podem variar de 2 a 6 horas, dependendo do itinerário escolhido. Oferecemos tours personalizados adaptados aos seus interesses e ritmo.",
    answerEn: "Tours can vary from 2 to 6 hours, depending on the chosen itinerary. We offer customized tours adapted to your interests and pace.",
    keywords: "duração,tempo,horas,tour,passeio,ilha",
  },
  {
    service: "tours",
    questionPt: "Quais são os principais pontos de interesse do tour?",
    questionEn: "What are the main points of interest on the tour?",
    answerPt: "Visitamos a Caldeira, Vulcão dos Capelinhos, Porto Pim, Marina da Horta, miradouros panorâmicos e muito mais. O itinerário pode ser personalizado.",
    answerEn: "We visit the Caldeira, Capelinhos Volcano, Porto Pim, Marina da Horta, panoramic viewpoints and much more. The itinerary can be customized.",
    keywords: "caldeira,capelinhos,vulcão,porto pim,marina,pontos,interesse,visitar",
  },
  {
    service: "tours",
    questionPt: "A carrinha de tours é mesmo elétrica?",
    questionEn: "Is the tour van really electric?",
    answerPt: "Sim! Usamos uma carrinha 100% elétrica de 9 lugares, contribuindo para um turismo sustentável e ecológico nos Açores.",
    answerEn: "Yes! We use a 100% electric 9-seater van, contributing to sustainable and ecological tourism in the Azores.",
    keywords: "elétrica,sustentável,carrinha,van,ecológico,9 lugares,tour",
  },
  {
    service: "tours",
    questionPt: "Posso personalizar o meu tour?",
    questionEn: "Can I customize my tour?",
    answerPt: "Absolutamente! Oferecemos tours personalizados adaptados aos seus interesses, ritmo e tempo disponível. Contacte-nos para planear o seu tour ideal.",
    answerEn: "Absolutely! We offer customized tours adapted to your interests, pace and available time. Contact us to plan your ideal tour.",
    keywords: "personalizado,customizado,itinerário,tour,interesses",
  },
  {
    service: "tours",
    questionPt: "Os tours incluem guia?",
    questionEn: "Do tours include a guide?",
    answerPt: "Sim! Todos os tours incluem um guia local experiente que conhece a ilha, a sua história e os melhores locais para visitar.",
    answerEn: "Yes! All tours include an experienced local guide who knows the island, its history and the best places to visit.",
    keywords: "guia,local,experiente,história,tour",
  },
  {
    service: "tours",
    questionPt: "O tour inclui recolha no alojamento?",
    questionEn: "Does the tour include pickup from accommodation?",
    answerPt: "Sim! Para clientes do nosso alojamento, oferecemos recolha e entrega gratuita. Para outros clientes, podemos combinar um ponto de encontro.",
    answerEn: "Yes! For guests of our accommodation, we offer free pickup and drop-off. For other clients, we can arrange a meeting point.",
    keywords: "recolha,pickup,alojamento,transfer,buscar,hotel",
  },
  {
    service: "transfers",
    questionPt: "Fazem transfer do aeroporto?",
    questionEn: "Do you do airport transfers?",
    answerPt: "Sim! Oferecemos transfer do aeroporto da Horta para qualquer ponto da ilha, incluindo os nossos apartamentos. Reserve com antecedência.",
    answerEn: "Yes! We offer transfer from Horta airport to any point on the island, including our apartments. Book in advance.",
    keywords: "aeroporto,transfer,transporte,chegada,partida,buscar",
  },
  {
    service: "transfers",
    questionPt: "A carrinha de transfer é elétrica?",
    questionEn: "Is the transfer van electric?",
    answerPt: "Sim! Usamos uma carrinha 100% elétrica de 9 lugares para todos os nossos transfers e tours, contribuindo para um turismo sustentável.",
    answerEn: "Yes! We use a 100% electric 9-seater van for all our transfers and tours, contributing to sustainable tourism.",
    keywords: "elétrica,carrinha,sustentável,ecológico,van,transfer",
  },
  {
    service: "transfers",
    questionPt: "Quanto custa o transfer do aeroporto?",
    questionEn: "How much does the airport transfer cost?",
    answerPt: "O preço do transfer depende do destino na ilha. Para clientes do nosso alojamento, oferecemos condições especiais. Contacte-nos para orçamento.",
    answerEn: "The transfer price depends on the destination on the island. For guests of our accommodation, we offer special conditions. Contact us for a quote.",
    keywords: "preço,custo,transfer,aeroporto,quanto,valor",
  },
  {
    service: "transfers",
    questionPt: "Quantas pessoas cabem no transfer?",
    questionEn: "How many people fit in the transfer?",
    answerPt: "A nossa carrinha elétrica tem capacidade para 9 passageiros. Para grupos maiores, podemos organizar múltiplos transfers.",
    answerEn: "Our electric van has capacity for 9 passengers. For larger groups, we can organize multiple transfers.",
    keywords: "pessoas,capacidade,lugares,passageiros,transfer,carrinha",
  },
  {
    service: "transfers",
    questionPt: "Podem esperar pelo meu voo?",
    questionEn: "Can you wait for my flight?",
    answerPt: "Sim! Monitorizamos os voos e ajustamos o horário de recolha conforme necessário. Não precisa de se preocupar com atrasos.",
    answerEn: "Yes! We monitor flights and adjust pickup time as needed. You don't need to worry about delays.",
    keywords: "voo,esperar,atraso,chegada,transfer,aeroporto",
  },
];

export async function seedFaqsIfEmpty() {
  if (!isDatabaseAvailable() || !db) {
    console.log("[SEED] Database not available, skipping FAQs seed");
    return;
  }
  
  try {
    console.log("[SEED] Checking FAQs database...");
    const existingFaqs = await db.select().from(faqs);
    console.log(`[SEED] Found ${existingFaqs.length} existing FAQs, seed has ${faqSeedData.length}`);
    
    if (existingFaqs.length === 0) {
      console.log("[SEED] Database empty, seeding FAQs...");
      for (const faq of faqSeedData) {
        await db.insert(faqs).values(faq);
      }
      console.log(`[SEED] Successfully seeded ${faqSeedData.length} FAQs`);
    } else if (existingFaqs.length < faqSeedData.length) {
      console.log(`[SEED] Database has fewer FAQs than seed (${existingFaqs.length} < ${faqSeedData.length}). Reseeding...`);
      await db.delete(faqs);
      for (const faq of faqSeedData) {
        await db.insert(faqs).values(faq);
      }
      console.log(`[SEED] Successfully reseeded ${faqSeedData.length} FAQs`);
    } else {
      console.log(`[SEED] FAQs database already has ${existingFaqs.length} entries, skipping seed`);
    }
  } catch (error) {
    console.error("[SEED] Error seeding FAQs:", error);
    throw error;
  }
}

export async function reseedFaqs() {
  if (!isDatabaseAvailable() || !db) {
    throw new Error("Database not available");
  }
  
  try {
    console.log("Clearing existing FAQs and reseeding...");
    await db.delete(faqs);
    for (const faq of faqSeedData) {
      await db.insert(faqs).values(faq);
    }
    console.log(`Successfully reseeded ${faqSeedData.length} FAQs`);
    return faqSeedData.length;
  } catch (error) {
    console.error("Error reseeding FAQs:", error);
    throw error;
  }
}
