export interface StaticFAQ {
  id: number;
  service: string;
  questionPt: string;
  questionEn: string;
  answerPt: string;
  answerEn: string;
  keywords: string;
}

export const staticFaqs: StaticFAQ[] = [
  { id: 33, service: "paintball", questionPt: "Qual é a idade mínima para jogar paintball?", questionEn: "What is the minimum age to play paintball?", answerPt: "A idade mínima é 10 anos. Menores devem estar acompanhados por um adulto responsável.", answerEn: "The minimum age is 10 years old. Minors must be accompanied by a responsible adult.", keywords: "idade,mínima,anos,criança,menor,paintball,jogar" },
  { id: 34, service: "paintball", questionPt: "O equipamento de paintball está incluído no preço?", questionEn: "Is paintball equipment included in the price?", answerPt: "Sim! O preço inclui máscara de proteção, marcador (arma), colete e bolas de tinta. Todo o equipamento necessário está incluído.", answerEn: "Yes! The price includes protective mask, marker (gun), vest and paintballs. All necessary equipment is included.", keywords: "equipamento,incluído,preço,máscara,marcador,colete,bolas,material" },
  { id: 35, service: "paintball", questionPt: "Preciso de reservar paintball com antecedência?", questionEn: "Do I need to book paintball in advance?", answerPt: "Sim, recomendamos reservar pelo menos 24 horas antes para garantir disponibilidade. Pode reservar online, por telefone (+351 934 993 770) ou WhatsApp (+351 969 519 950).", answerEn: "Yes, we recommend booking at least 24 hours in advance to ensure availability. You can book online, by phone (+351 934 993 770) or WhatsApp (+351 969 519 950).", keywords: "reservar,antecedência,marcação,agendar,disponibilidade,paintball" },
  { id: 36, service: "paintball", questionPt: "Onde fica o campo de paintball?", questionEn: "Where is the paintball field located?", answerPt: "Temos um campo exclusivo preparado na Ilha do Faial, Açores. O local exato é comunicado após a reserva para garantir a sua privacidade.", answerEn: "We have an exclusive prepared field on Faial Island, Azores. The exact location is communicated after booking to ensure privacy.", keywords: "onde,localização,campo,faial,açores,local,paintball" },
  { id: 37, service: "paintball", questionPt: "As bolas de paintball são biodegradáveis?", questionEn: "Are paintball balls biodegradable?", answerPt: "Sim! As nossas bolas de Paintball e Gelblaster são biodegradáveis. Depois de uma normal chuvinha, a tinta desaparece completamente, não deixando vestígios na paisagem.", answerEn: "Yes! Our Paintball and Gelblaster balls are biodegradable. After a normal rain, the paint disappears completely, leaving no traces in the landscape.", keywords: "biodegradável,ecológico,tinta,ambiente,sustentável,paintball" },
  { id: 38, service: "paintball", questionPt: "O paintball dói muito?", questionEn: "Does paintball hurt a lot?", answerPt: "As bolas de paintball podem causar um ligeiro impacto, mas com o equipamento de proteção fornecido, é seguro e confortável. Se preferir algo sem impacto, experimente o Lasertag!", answerEn: "Paintball balls can cause a slight impact, but with the protective equipment provided, it's safe and comfortable. If you prefer no impact, try Lasertag!", keywords: "dói,dor,impacto,seguro,proteção,paintball" },
  { id: 39, service: "paintball", questionPt: "Qual a diferença entre Paintball, Gelblaster, Lasertag e Nerfs?", questionEn: "What is the difference between Paintball, Gelblaster, Lasertag and Nerfs?", answerPt: "Paintball usa bolas de tinta com impacto médio. Gelblaster usa gel biodegradável com impacto leve. Lasertag usa sensores infravermelhos sem impacto. Nerfs usam dardos de espuma suaves. Todos são seguros e divertidos!", answerEn: "Paintball uses paint balls with medium impact. Gelblaster uses biodegradable gel with light impact. Lasertag uses infrared sensors with no impact. Nerfs use soft foam darts. All are safe and fun!", keywords: "diferença,paintball,gelblaster,lasertag,nerfs,comparar,tipo" },
  { id: 40, service: "paintball", questionPt: "Quantas pessoas podem jogar paintball?", questionEn: "How many people can play paintball?", answerPt: "Podemos organizar jogos para grupos de 6 a 40+ pessoas. Para grupos maiores, contacte-nos para um orçamento personalizado para eventos ou teambuilding.", answerEn: "We can organize games for groups of 6 to 40+ people. For larger groups, contact us for a personalized quote for events or teambuilding.", keywords: "pessoas,grupo,quantos,capacidade,paintball,teambuilding" },
  { id: 41, service: "lasertag", questionPt: "O LaserTag dói como o paintball?", questionEn: "Does LaserTag hurt like paintball?", answerPt: "Não! O LaserTag utiliza sensores infravermelhos, sem qualquer impacto físico. É perfeito para todas as idades e para quem prefere uma experiência sem contacto.", answerEn: "No! LaserTag uses infrared sensors, with no physical impact. It's perfect for all ages and for those who prefer a no-contact experience.", keywords: "lasertag,dói,dor,impacto,idade,criança,contacto" },
  { id: 42, service: "lasertag", questionPt: "Posso jogar LaserTag à noite?", questionEn: "Can I play LaserTag at night?", answerPt: "Sim! O LaserTag é ainda mais espetacular à noite com os efeitos das luzes dos sensores. Os jogos noturnos são muito populares!", answerEn: "Yes! LaserTag is even more spectacular at night with the sensor light effects. Night games are very popular!", keywords: "lasertag,noite,noturno,escuro,luzes,efeitos" },
  { id: 43, service: "accommodation", questionPt: "Onde fica a Casa da Travessa?", questionEn: "Where is Casa da Travessa located?", answerPt: "A Casa da Travessa fica na Rua Conselheiro Medeiros, 27, no centro histórico da Horta, Faial. A 2 minutos a pé da marina.", answerEn: "Casa da Travessa is located at Rua Conselheiro Medeiros, 27, in the historic center of Horta, Faial. 2 minutes walk from the marina.", keywords: "localização,onde,morada,endereço,centro,marina,horta" },
  { id: 44, service: "accommodation", questionPt: "O alojamento tem estacionamento?", questionEn: "Does the accommodation have parking?", answerPt: "Temos estacionamento gratuito disponível para hóspedes. O estacionamento está sujeito à disponibilidade.", answerEn: "We have free parking available for guests. Parking is subject to availability.", keywords: "estacionamento,carro,parking,gratuito,disponível" },
  { id: 45, service: "accommodation", questionPt: "O alojamento é adequado para famílias com crianças?", questionEn: "Is the accommodation suitable for families with children?", answerPt: "Sim! A Casa da Travessa é perfeita para famílias. Temos apartamentos espaçosos, equipados com cozinha completa e ambiente seguro para crianças.", answerEn: "Yes! Casa da Travessa is perfect for families. We have spacious apartments, equipped with full kitchen and safe environment for children.", keywords: "família,crianças,bebé,seguro,adequado,espaço" },
  { id: 46, service: "accommodation", questionPt: "O alojamento tem Wi-Fi?", questionEn: "Does the accommodation have Wi-Fi?", answerPt: "Sim! Todos os apartamentos têm Wi-Fi gratuito de alta velocidade.", answerEn: "Yes! All apartments have free high-speed Wi-Fi.", keywords: "wifi,internet,gratuito,velocidade,conectividade" },
  { id: 47, service: "accommodation", questionPt: "A Casa da Travessa tem cozinha?", questionEn: "Does Casa da Travessa have a kitchen?", answerPt: "Sim! Todos os apartamentos incluem cozinha totalmente equipada com frigorífico, fogão, micro-ondas e utensílios de cozinha.", answerEn: "Yes! All apartments include a fully equipped kitchen with fridge, stove, microwave and cooking utensils.", keywords: "cozinha,equipada,frigorífico,fogão,utensílios,cozinhar" },
  { id: 48, service: "tourism", questionPt: "Que atividades turísticas oferecem?", questionEn: "What tourist activities do you offer?", answerPt: "Oferecemos Paintball, LaserTag, GelBlaster, Nerfs, Caiaque, SUP (Stand Up Paddle), Tours de Carrinha Elétrica pela ilha do Faial, e transferes.", answerEn: "We offer Paintball, LaserTag, GelBlaster, Nerfs, Kayak, SUP (Stand Up Paddle), Electric Van Tours around Faial island, and transfers.", keywords: "atividades,turismo,oferecem,serviços,animação,experiências" },
  { id: 49, service: "tourism", questionPt: "Onde posso alugar caiaque ou SUP?", questionEn: "Where can I rent kayak or SUP?", answerPt: "Pode alugar caiaque ou SUP na Marina da Horta ou na baía de Porto Pim. Ambos os locais oferecem águas calmas e vistas espetaculares!", answerEn: "You can rent kayak or SUP at Marina da Horta or Porto Pim bay. Both locations offer calm waters and spectacular views!", keywords: "caiaque,sup,alugar,marina,porto pim,paddle" },
  { id: 50, service: "tourism", questionPt: "Os tours incluem guia?", questionEn: "Do tours include a guide?", answerPt: "Sim! Todos os tours de carrinha incluem motorista/guia que conhece profundamente a ilha e partilha histórias e curiosidades sobre cada local visitado.", answerEn: "Yes! All van tours include a driver/guide who knows the island deeply and shares stories and curiosities about each visited location.", keywords: "tour,guia,incluído,motorista,explicações,história" },
  { id: 51, service: "tourism", questionPt: "A carrinha dos tours é elétrica?", questionEn: "Is the tour van electric?", answerPt: "Sim! Utilizamos uma carrinha 100% elétrica, zero emissões. Estamos comprometidos com o turismo sustentável e a preservação dos Açores.", answerEn: "Yes! We use a 100% electric van, zero emissions. We are committed to sustainable tourism and the preservation of the Azores.", keywords: "elétrica,carrinha,sustentável,emissões,ecológico,ambiente" },
  { id: 52, service: "tattoo", questionPt: "Quem faz as tatuagens na Azores4fun?", questionEn: "Who does the tattoos at Azores4fun?", answerPt: "A nossa artista residente é a Catarina Gomes, tatuadora profissional com anos de experiência em diversos estilos, desde minimalismo a realismo.", answerEn: "Our resident artist is Catarina Gomes, a professional tattoo artist with years of experience in various styles, from minimalism to realism.", keywords: "tatuadora,artista,catarina,gomes,quem,profissional" },
  { id: 53, service: "tattoo", questionPt: "É necessário marcar tatuagem com antecedência?", questionEn: "Do I need to book a tattoo in advance?", answerPt: "Sim, recomendamos agendar pelo menos 1 semana antes, especialmente para trabalhos maiores. Contacte-nos por WhatsApp ou email para agendar.", answerEn: "Yes, we recommend booking at least 1 week in advance, especially for larger works. Contact us via WhatsApp or email to schedule.", keywords: "marcar,agendar,antecedência,reservar,tatuagem,marcação" },
  { id: 54, service: "tattoo", questionPt: "Fazem piercings também?", questionEn: "Do you do piercings too?", answerPt: "Sim! Oferecemos serviços profissionais de piercing com materiais esterilizados e jóias de qualidade. Orelhas, nariz, sobrancelha, e mais.", answerEn: "Yes! We offer professional piercing services with sterilized materials and quality jewelry. Ears, nose, eyebrow, and more.", keywords: "piercing,furos,jóias,orelha,nariz,sobrancelha" },
  { id: 55, service: "tattoo", questionPt: "Qual é o preço mínimo para tatuagem?", questionEn: "What is the minimum price for a tattoo?", answerPt: "O preço mínimo para tatuagem é 60€. O valor final depende do tamanho, complexidade e local do corpo. Contacte-nos para orçamento personalizado.", answerEn: "The minimum price for a tattoo is €60. The final value depends on size, complexity and body location. Contact us for a personalized quote.", keywords: "preço,custo,valor,mínimo,tatuagem,quanto custa" },
  { id: 56, service: "events", questionPt: "Organizam festas de aniversário?", questionEn: "Do you organize birthday parties?", answerPt: "Sim! Organizamos festas de aniversário completas com atividades como paintball, lasertag, jogos e muito mais. Perfeito para crianças e adultos!", answerEn: "Yes! We organize complete birthday parties with activities like paintball, lasertag, games and much more. Perfect for children and adults!", keywords: "aniversário,festa,organizar,crianças,adultos,celebração" },
  { id: 57, service: "events", questionPt: "Oferecem pacotes para despedidas de solteiro?", questionEn: "Do you offer bachelor party packages?", answerPt: "Sim! Temos pacotes especiais para despedidas de solteiro/a com atividades emocionantes, tours pela ilha e experiências personalizadas.", answerEn: "Yes! We have special packages for bachelor/bachelorette parties with exciting activities, island tours and personalized experiences.", keywords: "despedida,solteiro,solteira,pacote,grupo,festa" },
  { id: 58, service: "events", questionPt: "Fazem team building para empresas?", questionEn: "Do you do team building for companies?", answerPt: "Sim! Organizamos eventos de team building com atividades como paintball, lasertag, tours e desafios personalizados para empresas de todos os tamanhos.", answerEn: "Yes! We organize team building events with activities like paintball, lasertag, tours and personalized challenges for companies of all sizes.", keywords: "teambuilding,empresa,corporativo,grupo,equipa,eventos" },
  { id: 59, service: "shop", questionPt: "O que vendem na loja Azores4fun?", questionEn: "What do you sell in the Azores4fun shop?", answerPt: "Vendemos merchandising Azores4fun (t-shirts, bonés, canecas), produtos regionais açorianos, artesanato local e lembranças dos Açores.", answerEn: "We sell Azores4fun merchandise (t-shirts, caps, mugs), Azorean regional products, local handicrafts and Azores souvenirs.", keywords: "loja,comprar,merchandising,produtos,souvenirs,lembranças" },
  { id: 60, service: "shop", questionPt: "Onde fica a loja física?", questionEn: "Where is the physical store?", answerPt: "A loja física fica na Rua Conselheiro Medeiros, 27, no centro da Horta, Faial. O mesmo edifício da Casa da Travessa.", answerEn: "The physical store is at Rua Conselheiro Medeiros, 27, in the center of Horta, Faial. The same building as Casa da Travessa.", keywords: "loja,localização,onde,morada,horta,física" },
  { id: 61, service: "property", questionPt: "Oferecem gestão de propriedades?", questionEn: "Do you offer property management?", answerPt: "Sim! Oferecemos serviços completos de gestão imobiliária incluindo aluguer de curta e longa duração, manutenção e gestão de reservas.", answerEn: "Yes! We offer complete property management services including short and long term rentals, maintenance and booking management.", keywords: "gestão,imobiliária,propriedade,aluguer,arrendamento,manutenção" },
  { id: 62, service: "property", questionPt: "Gerem propriedades para Airbnb?", questionEn: "Do you manage properties for Airbnb?", answerPt: "Sim! Gerimos propriedades para plataformas como Airbnb e Booking.com. Tratamos de tudo: fotos, anúncios, reservas, limpeza e check-in/out.", answerEn: "Yes! We manage properties for platforms like Airbnb and Booking.com. We handle everything: photos, listings, bookings, cleaning and check-in/out.", keywords: "airbnb,booking,gestão,alojamento local,plataformas" },
  { id: 63, service: "general", questionPt: "Qual é o horário de funcionamento?", questionEn: "What are your opening hours?", answerPt: "Estamos disponíveis das 9h às 19h, 7 dias por semana. Para atividades fora deste horário, contacte-nos previamente.", answerEn: "We are available from 9am to 7pm, 7 days a week. For activities outside these hours, please contact us in advance.", keywords: "horário,funcionamento,aberto,disponível,horas" },
  { id: 64, service: "general", questionPt: "Aceitam cartão de crédito?", questionEn: "Do you accept credit cards?", answerPt: "Sim! Aceitamos dinheiro, cartões de débito e crédito (Visa, Mastercard), e transferência bancária.", answerEn: "Yes! We accept cash, debit and credit cards (Visa, Mastercard), and bank transfer.", keywords: "pagamento,cartão,crédito,débito,dinheiro,multibanco" },
  { id: 65, service: "general", questionPt: "A Azores4fun tem certificação sustentável?", questionEn: "Does Azores4fun have sustainable certification?", answerPt: "Sim! Temos a certificação Marca Açores e estamos comprometidos com práticas de turismo sustentável, utilizando veículos elétricos e materiais biodegradáveis.", answerEn: "Yes! We have the Marca Açores certification and are committed to sustainable tourism practices, using electric vehicles and biodegradable materials.", keywords: "sustentável,marca açores,certificação,ecológico,ambiente,verde" },
  { id: 66, service: "general", questionPt: "Como posso contactar a Azores4fun?", questionEn: "How can I contact Azores4fun?", answerPt: "Pode contactar-nos por: Telefone (+351 934 993 770), WhatsApp (+351 969 519 950), Email (info@azores4fun.com), ou visitar-nos na Rua Conselheiro Medeiros 27, Horta.", answerEn: "You can contact us by: Phone (+351 934 993 770), WhatsApp (+351 969 519 950), Email (info@azores4fun.com), or visit us at Rua Conselheiro Medeiros 27, Horta.", keywords: "contacto,telefone,whatsapp,email,morada,falar" },
  { id: 67, service: "general", questionPt: "Falam inglês?", questionEn: "Do you speak English?", answerPt: "Sim! A nossa equipa é bilingue e atende em português e inglês. Também temos conhecimentos básicos de espanhol e francês.", answerEn: "Yes! Our team is bilingual and serves in Portuguese and English. We also have basic knowledge of Spanish and French.", keywords: "inglês,idioma,língua,bilingue,português,falar" },
  { id: 68, service: "transfers", questionPt: "Fazem transferes do aeroporto?", questionEn: "Do you do airport transfers?", answerPt: "Sim! Oferecemos transferes do/para o aeroporto da Horta em carrinha 100% elétrica. Reserve com antecedência para garantir disponibilidade.", answerEn: "Yes! We offer transfers to/from Horta airport in a 100% electric van. Book in advance to ensure availability.", keywords: "transfer,aeroporto,transporte,carrinha,buscar,levar" },
  { id: 69, service: "transfers", questionPt: "A carrinha de transferes é elétrica?", questionEn: "Is the transfer van electric?", answerPt: "Sim! Utilizamos exclusivamente uma carrinha 100% elétrica, contribuindo para a sustentabilidade ambiental dos Açores.", answerEn: "Yes! We exclusively use a 100% electric van, contributing to the environmental sustainability of the Azores.", keywords: "elétrica,carrinha,sustentável,transfer,ambiental,zero emissões" },
  { id: 70, service: "general", questionPt: "Posso falar com uma pessoa ao vivo?", questionEn: "Can I speak to a real person?", answerPt: "Claro! Pode ligar para +351 934 993 770 ou enviar mensagem pelo WhatsApp +351 969 519 950. A nossa equipa está disponível das 9h às 19h.", answerEn: "Of course! You can call +351 934 993 770 or send a message via WhatsApp +351 969 519 950. Our team is available from 9am to 7pm.", keywords: "pessoa,humano,falar,contacto,telefone,whatsapp,atendimento" },
  { id: 71, service: "tourism", questionPt: "Quais são os principais pontos turísticos do Faial?", questionEn: "What are the main tourist attractions in Faial?", answerPt: "Os destaques incluem o Vulcão dos Capelinhos, Caldeira do Faial, Marina da Horta com os famosos murais, Porto Pim, e a vista para o Pico.", answerEn: "Highlights include Capelinhos Volcano, Caldeira do Faial, Horta Marina with famous murals, Porto Pim, and the view to Pico island.", keywords: "pontos turísticos,atrações,capelinhos,caldeira,marina,visitar" },
  { id: 72, service: "tourism", questionPt: "Quanto tempo demora o tour pela ilha?", questionEn: "How long does the island tour take?", answerPt: "O tour completo pela ilha dura aproximadamente 4-5 horas, visitando Capelinhos, Caldeira, miradouros e paragens para fotos.", answerEn: "The complete island tour lasts approximately 4-5 hours, visiting Capelinhos, Caldeira, viewpoints and photo stops.", keywords: "tour,duração,tempo,horas,ilha,completo" },
  { id: 73, service: "accommodation", questionPt: "Qual é a política de cancelamento?", questionEn: "What is the cancellation policy?", answerPt: "Cancelamento gratuito até 7 dias antes da chegada. Para cancelamentos tardios, consulte as condições específicas da sua reserva.", answerEn: "Free cancellation up to 7 days before arrival. For late cancellations, please check the specific conditions of your booking.", keywords: "cancelamento,política,reembolso,anular,reserva" },
  { id: 74, service: "tattoo", questionPt: "Posso ver trabalhos anteriores?", questionEn: "Can I see previous work?", answerPt: "Sim! Visite a nossa página de Portfolio no website ou o Instagram @catarinagomestattoo para ver trabalhos da artista Catarina Gomes.", answerEn: "Yes! Visit our Portfolio page on the website or Instagram @catarinagomestattoo to see works by artist Catarina Gomes.", keywords: "portfolio,trabalhos,fotos,instagram,exemplos,galeria" },
  { id: 75, service: "events", questionPt: "Quantas pessoas cabem num evento?", questionEn: "How many people fit in an event?", answerPt: "Dependendo da atividade, podemos organizar eventos para 6 até 100+ pessoas. Contacte-nos para eventos maiores com orçamento personalizado.", answerEn: "Depending on the activity, we can organize events for 6 to 100+ people. Contact us for larger events with a personalized quote.", keywords: "pessoas,capacidade,grupo,evento,quantos,máximo" },
  { id: 76, service: "general", questionPt: "Têm seguro para as atividades?", questionEn: "Do you have insurance for the activities?", answerPt: "Sim! Todas as nossas atividades turísticas estão cobertas por seguro de responsabilidade civil, garantindo a segurança de todos os participantes.", answerEn: "Yes! All our tourist activities are covered by liability insurance, ensuring the safety of all participants.", keywords: "seguro,cobertura,segurança,responsabilidade,proteção" },
  { id: 77, service: "general", questionPt: "As atividades são adequadas para pessoas com mobilidade reduzida?", questionEn: "Are activities suitable for people with reduced mobility?", answerPt: "Algumas atividades como tours de carrinha são acessíveis. Para outras atividades, contacte-nos para avaliarmos adaptações possíveis.", answerEn: "Some activities like van tours are accessible. For other activities, contact us to assess possible adaptations.", keywords: "mobilidade,acessível,cadeira rodas,adaptado,deficiência" },
  { id: 78, service: "tourism", questionPt: "Posso ver baleias e golfinhos nos Açores?", questionEn: "Can I see whales and dolphins in the Azores?", answerPt: "Sim! Os Açores são um dos melhores locais do mundo para observação de cetáceos. Recomendamos operadores especializados de whale watching.", answerEn: "Yes! The Azores are one of the best places in the world for whale watching. We recommend specialized whale watching operators.", keywords: "baleias,golfinhos,cetáceos,whale watching,observação" },
  { id: 79, service: "general", questionPt: "Qual a melhor época para visitar o Faial?", questionEn: "What is the best time to visit Faial?", answerPt: "O Faial pode ser visitado todo o ano. Verão (Jun-Set) tem tempo mais quente e estável. Primavera e Outono são excelentes para atividades ao ar livre com menos turistas.", answerEn: "Faial can be visited year-round. Summer (Jun-Sep) has warmer and more stable weather. Spring and Autumn are excellent for outdoor activities with fewer tourists.", keywords: "melhor época,quando visitar,clima,tempo,estação" },
  { id: 80, service: "general", questionPt: "Como chegar ao Faial?", questionEn: "How to get to Faial?", answerPt: "Pode voar para o Aeroporto da Horta (HOR) via Lisboa, Ponta Delgada ou Terceira com SATA/Azores Airlines. Também há ferry entre ilhas.", answerEn: "You can fly to Horta Airport (HOR) via Lisbon, Ponta Delgada or Terceira with SATA/Azores Airlines. There's also inter-island ferry.", keywords: "chegar,viajar,avião,ferry,aeroporto,transporte" }
];

export function getFaqsByService(service: string): StaticFAQ[] {
  return staticFaqs.filter(faq => faq.service === service);
}

export function getAllFaqs(): StaticFAQ[] {
  return staticFaqs;
}
